name: Update

on:
  schedule:
  - cron:  "*/15 * * * *"

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  update:
    # Name the Job
    name: Update list of vaccine locations
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Run program
        run: go run cmd/vaccine-finder/main.go
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: dist
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
